### PR TITLE
Replace if chains with case

### PR DESCRIPTION
**Pull request by soliton-**
### Preflight Checklist
I have:

 - [x] Read the Contributor's Guidelines.
 - [ ] Updated the examples as necessary.
 - [ ] Updated the documentation as necessary.
 - [x] GPG signed my commits.

### CODE REVIEW

**Review by dak180 — CHANGES_REQUESTED** [review]
Two changes: for the main `if` statement I do not see any need to change the conditional and for the formatting of the `case` statement please match the formatting as seen in the existing [autorevision.sh#L79](/Autorevision/autorevision/blob/master/autorevision.sh#L79).

**Comment by soliton-** [comment]
I don't see the point of the negation but sure if that's an unwritten style guide. Will fix the case formatting. Couldn't really figure out the preferred style of case statements.

**Review by dak180 — CHANGES_REQUESTED** [review]
I just ran the test script and got the following output:

```sh
sed -e 's:&&ARVERSION&&:1.21:g' autorevision.sh > autorevision
chmod +x autorevision
a2x --attribute="revdate=2020-09-07" --attribute="revnumber=1.21" -f manpage autorevision.asciidoc
gzip --no-name < autorevision.1 > autorevision.1.gz
./autorevision.sh -f -t sed -o autorevision.cache > autorevision.sed
error: sed is not a valid output type.
make: *** [autorevision.sed] Error 1
```

**Comment by soliton-** [comment]
Ah my apologies, I must have mixed up the edit with an older version without that output type. Fixed in the last commit.

**Comment by dak180** [comment]
Hopefully one last thing; I noticed that the order that some of the options are in has changed; could you put them back (unless there is a reason for this I am unaware of) to make it easier to check that all of them are present?

**Comment by soliton-** [comment]
Could you point out where I changed the order? I don't see it.

**Comment by dak180** [comment]
@soliton- I think it was my not yet awake brain looking at the wrong thing.

**Pull request merged**
